/**
 * Error Codes
 *
 * Centralized error codes for consistent API responses.
 */
export const ErrorCodes = {
  // Auth errors (1xxx)
  AUTH_INVALID_TOKEN: 'AUTH_1001',
  AUTH_TOKEN_EXPIRED: 'AUTH_1002',
  AUTH_UNAUTHORIZED: 'AUTH_1003',
  AUTH_FORBIDDEN: 'AUTH_1004',
  AUTH_USER_NOT_FOUND: 'AUTH_1005',
  AUTH_INVALID_CREDENTIALS: 'AUTH_1006',
  AUTH_EMAIL_IN_USE: 'AUTH_1007',
  AUTH_PHONE_IN_USE: 'AUTH_1008',
  AUTH_OTP_EXPIRED: 'AUTH_1009',
  AUTH_OTP_INVALID: 'AUTH_1010',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_1011',
  AUTH_INVALID_EMAIL: 'AUTH_1012',
  AUTH_WEAK_PASSWORD: 'AUTH_1013',
  AUTH_REGISTRATION_FAILED: 'AUTH_1014',
  AUTH_TOKEN_REVOKED: 'AUTH_1015',
  AUTH_GOOGLE_SIGNIN_FAILED: 'AUTH_1016',
  AUTH_DELETE_FAILED: 'AUTH_1017',

  // User errors (2xxx)
  USER_NOT_FOUND: 'USER_2001',
  USER_ALREADY_EXISTS: 'USER_2002',
  USER_INVALID_ROLE: 'USER_2003',
  USER_PROFILE_INCOMPLETE: 'USER_2004',

  // Shop errors (3xxx)
  SHOP_NOT_FOUND: 'SHOP_3001',
  SHOP_ALREADY_EXISTS: 'SHOP_3002',
  SHOP_NOT_APPROVED: 'SHOP_3003',
  SHOP_CLOSED: 'SHOP_3004',
  SHOP_SUBSCRIPTION_EXPIRED: 'SHOP_3005',
  SHOP_NOT_OWNER: 'SHOP_3006',

  // Product errors (4xxx)
  PRODUCT_NOT_FOUND: 'PRODUCT_4001',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_4002',
  PRODUCT_UNAVAILABLE: 'PRODUCT_4003',
  PRODUCT_PRICE_CHANGED: 'PRODUCT_4004',

  // Category errors (4xxx)
  CATEGORY_NOT_FOUND: 'CATEGORY_4501',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_4502',

  // Cart errors (5xxx)
  CART_EMPTY: 'CART_5001',
  CART_ITEM_NOT_FOUND: 'CART_5002',
  CART_MIXED_SHOPS: 'CART_5003',
  CART_UNAUTHORIZED: 'CART_5401',
  CART_FORBIDDEN: 'CART_5403',
  CART_INTERNAL_ERROR: 'CART_5500',

  // Order errors (6xxx)
  ORDER_NOT_FOUND: 'ORDER_6001',
  ORDER_INVALID_STATUS: 'ORDER_6002',
  ORDER_ALREADY_CANCELLED: 'ORDER_6003',
  ORDER_CANNOT_CANCEL: 'ORDER_6004',
  ORDER_ALREADY_ASSIGNED: 'ORDER_6005',
  ORDER_NOT_ASSIGNED: 'ORDER_6006',

  // Payment errors (7xxx)
  PAYMENT_FAILED: 'PAYMENT_7001',
  PAYMENT_INVALID_METHOD: 'PAYMENT_7002',
  PAYMENT_ALREADY_PAID: 'PAYMENT_7003',
  PAYMENT_REFUND_FAILED: 'PAYMENT_7004',
  PAYMENT_WEBHOOK_INVALID: 'PAYMENT_7005',

  // Wallet errors (8xxx)
  WALLET_NOT_FOUND: 'WALLET_8001',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_8002',
  WALLET_PAYOUT_FAILED: 'WALLET_8003',
  WALLET_MINIMUM_PAYOUT: 'WALLET_8004',

  // Shipper errors (9xxx)
  SHIPPER_NOT_FOUND: 'SHIPPER_9001',
  SHIPPER_NOT_AVAILABLE: 'SHIPPER_9002',
  SHIPPER_ALREADY_ASSIGNED: 'SHIPPER_9003',
  SHIPPER_NOT_APPROVED: 'SHIPPER_9004',

  // Voucher errors (10xxx) - Unified semantic naming
  // NOT FOUND (404)
  VOUCHER_NOT_FOUND: 'VOUCHER_NOT_FOUND',
  VOUCHER_USAGE_NOT_FOUND: 'VOUCHER_USAGE_NOT_FOUND',

  // INACTIVE/EXPIRED (400)
  VOUCHER_INACTIVE: 'VOUCHER_INACTIVE',
  VOUCHER_EXPIRED: 'VOUCHER_EXPIRED',
  VOUCHER_NOT_STARTED: 'VOUCHER_NOT_STARTED',

  // LIMITS (400)
  VOUCHER_TOTAL_LIMIT_REACHED: 'VOUCHER_TOTAL_LIMIT_REACHED',
  VOUCHER_USER_LIMIT_REACHED: 'VOUCHER_USER_LIMIT_REACHED',

  // CONDITIONS (400)
  VOUCHER_MIN_ORDER_NOT_MET: 'VOUCHER_MIN_ORDER_NOT_MET',
  VOUCHER_NOT_APPLICABLE: 'VOUCHER_NOT_APPLICABLE',
  VOUCHER_WRONG_SHOP: 'VOUCHER_WRONG_SHOP',

  // CONFLICT (409)
  VOUCHER_CODE_EXISTS: 'VOUCHER_CODE_EXISTS',
  VOUCHER_ALREADY_APPLIED: 'VOUCHER_ALREADY_APPLIED',

  // VALIDATION (400)
  VOUCHER_INVALID_DATE_RANGE: 'VOUCHER_INVALID_DATE_RANGE',
  VOUCHER_INVALID_VALUE: 'VOUCHER_INVALID_VALUE',
  VOUCHER_INVALID_TYPE: 'VOUCHER_INVALID_TYPE',

  // PERMISSION (403)
  VOUCHER_NOT_OWNED: 'VOUCHER_NOT_OWNED',
  VOUCHER_CANNOT_DELETE: 'VOUCHER_CANNOT_DELETE',
  VOUCHER_CANNOT_MODIFY: 'VOUCHER_CANNOT_MODIFY',

  // INTERNAL (500)
  VOUCHER_APPLY_FAILED: 'VOUCHER_APPLY_FAILED',
  VOUCHER_TRANSACTION_FAILED: 'VOUCHER_TRANSACTION_FAILED',

  // General errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
